version: "3.5"
services:
    react:
      container_name: platform_react
      build:
        context: ./react
      restart: always
      privileged: true
      command: /bin/bash -c "cd /var/www/maev02_reader_front;yarn install;yarn run dev"
      volumes:
        - ${APP_CODE_PATH_HOST}:/var/www
      ports:
        - 4000:443
      networks:
        - server_netsserver
    golang:
      container_name: platform_golang
      build:
        context: ./golang
      restart: always
      privileged: true
#      stdin_open: true # docker run -i
#      tty: true        # docker run -t
      command: /bin/bash -c "cd /var/www/maev02_reader_backend;go mod vendor;go run main.go;"
      volumes:
        - ${APP_CODE_PATH_HOST}:/var/www
      ports:
        - 4001:2000
      networks:
        - server_netsserver
    python:
      container_name: platform_flask
      build:
        context: ./python
      restart: always
      #command: /bin/bash -c "cd /var/www/maev02_reader_crawler;source venv/bin/activate;pip install -r requirements.txt;python main.py"
      #command: /bin/bash -c "cd /var/www/maev02_reader_crawler;source venv/bin/activate;cp supervisord.conf /etc/;;unlink /tmp/supervisor.sock;supervisord -c /etc/supervisord.conf"
      stdin_open: true
      tty: true 
      privileged: true
      volumes:
        - ${APP_CODE_PATH_HOST}:/var/www
        - /etc/localtime:/etc/localtime:ro
      ports:
        - 4002:4000
      networks:
        - server_netsserver
    chrome:
      container_name: platform_chrome
      image: selenium/standalone-chrome:103.0 
      shm_size: '2gb'
      restart: always
      ports:
        - 4444:4444
        - 7900:7900
      networks:
        - server_netsserver

    
networks:
  server_netsserver:
    external:
      name: server_netsserver
